# Exploring factors affecting infant sleep patterns: The role of feeding and developement

**Course:** Data Science - Final project

**Author:** Nikolay Atanasov | **Date:** April 13

---

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

## 1. Introduction
This project aims to explore factors that influence **infant sleep patterns** using multiple datasets.

In [2]:
import os
os.listdir()

['.git',
 '.ipynb_checkpoints',
 '.virtual_documents',
 'anaconda_projects',
 'Dataset_maternal_mental_health_infant_sleep.csv',
 'Data_Science_project.ipynb',
 'Weights heights of Infants with respect to method of feeding.xlsx']

In [4]:
sleep_df = pd.read_csv("Dataset_maternal_mental_health_infant_sleep.csv", encoding = "latin1")
feeding_df = pd.read_excel("Weights heights of Infants with respect to method of feeding.xlsx")

C:\Users\liyag\AppData\Local\Temp\ipykernel_9112\2940373529.py:1: DtypeWarning: Columns (6,61) have mixed types. Specify dtype option on import or set low_memory=False.
  sleep_df = pd.read_csv("Dataset_maternal_mental_health_infant_sleep.csv", encoding = "latin1")

In [6]:
sleep_df.head()

,Participant_number,Type_parents,Birth_1mth_M_inclusion,Birth_12mth_M_inclusion,Age,Marital_status,Marital_status_Autre,Marital_status_edit,Education,Gestationnal_age,...,IBQ_R_VSF_10_bb1,IBQ_R_VSF_16_bb1,IBQ_R_VSF_17_bb1,IBQ_R_VSF_28_bb1,IBQ_R_VSF_29_bb1,IBQ_R_VSF_32_bb1,IBQ_R_VSF_33_bb1,Sleep_night_duration_bb1,night_awakening_number_bb1,how_falling_asleep_bb1
0,1.0,1.0,1.0,1.0,34.0,2.0,NaN,2.0,5.0,37.0,...,NaN,7.0,NaN,NaN,7.0,6.0,NaN,10:00,3.0,2.0
1,2.0,1.0,1.0,1.0,33.0,2.0,NaN,2.0,5.0,42.0,...,2.0,3.0,2.0,2.0,2.0,3.0,4.0,11:00,0.0,4.0
2,3.0,1.0,1.0,1.0,37.0,2.0,NaN,2.0,5.0,41.0,...,4.0,4.0,3.0,1.0,4.0,NaN,NaN,12:00,1.0,2.0
3,4.0,1.0,1.0,1.0,31.0,2.0,NaN,2.0,5.0,37.5,...,1.0,3.0,NaN,NaN,NaN,5.0,NaN,11:00,2.0,1.0
4,5.0,1.0,1.0,1.0,36.0,1.0,NaN,1.0,5.0,40.0,...,4.0,2.0,2.0,4.0,5.0,6.0,6.0,10:30,1.0,4.0

In [7]:
feeding_df.head()

   S/n  Weight  Height    Month    Breastfeeding Partern
0    1     4.0    17.0  Month 1  Exclusive Breastfeeding
1    2     4.9    18.5  Month 1  Exclusive Breastfeeding
2    3     5.2    16.0  Month 1  Exclusive Breastfeeding
3    4     4.5    18.0  Month 1  Exclusive Breastfeeding
4    5     5.5    19.0  Month 1  Exclusive Breastfeeding

In [8]:
sleep_df.shape

(1048292, 64)

In [9]:
feeding_df.shape

(720, 5)

In [11]:
sleep_df.columns

Index(['Participant_number', 'Type_parents', 'Birth_1mth_M_inclusion',
       'Birth_12mth_M_inclusion', 'Age', 'Marital_status',
       'Marital_status_Autre', 'Marital_status_edit', 'Education',
       'Gestationnal_age', 'Type_pregnancy', 'sex_baby1', 'CBTS_M_3',
       'CBTS_M_4', 'CBTS_M_5', 'CBTS_M_6', 'CBTS_M_7', 'CBTS_M_8', 'CBTS_M_9',
       'CBTS_M_10', 'CBTS_M_11', 'CBTS_M_12', 'CBTS_13', 'CBTS_14', 'CBTS_15',
       'CBTS_16', 'CBTS_17', 'CBTS_18', 'CBTS_19', 'CBTS_20', 'CBTS_21',
       'CBTS_22', 'EPDS_1', 'EPDS_2', 'EPDS_3', 'EPDS_4', 'EPDS_5', 'EPDS_6',
       'EPDS_7', 'EPDS_8', 'EPDS_9', 'EPDS_10', 'HADS_1', 'HADS_3', 'HADS_5',
       'HADS_7', 'HADS_9', 'HADS_11', 'HADS_13', 'Child_survey_participation',
       'Age_bb', 'IBQ_R_VSF_3_bb1', 'IBQ_R_VSF_4_bb1', 'IBQ_R_VSF_9_bb1',
       'IBQ_R_VSF_10_bb1', 'IBQ_R_VSF_16_bb1', 'IBQ_R_VSF_17_bb1',
       'IBQ_R_VSF_28_bb1', 'IBQ_R_VSF_29_bb1', 'IBQ_R_VSF_32_bb1',
       'IBQ_R_VSF_33_bb1', 'Sleep_night_duration_bb1',
       'night_awakening_number_bb1', 'how_falling_asleep_bb1'],
      dtype='object')

In [12]:
feeding_df.columns

Index(['S/n', 'Weight', 'Height', 'Month', 'Breastfeeding Partern'], dtype='object')

In [13]:
sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048292 entries, 0 to 1048291
Data columns (total 64 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Participant_number          410 non-null    float64
 1   Type_parents                410 non-null    float64
 2   Birth_1mth_M_inclusion      410 non-null    float64
 3   Birth_12mth_M_inclusion     410 non-null    float64
 4   Age                         410 non-null    float64
 5   Marital_status              410 non-null    float64
 6   Marital_status_Autre        2 non-null      object
 7   Marital_status_edit         410 non-null    float64
 8   Education                   410 non-null    float64
 9   Gestationnal_age            410 non-null    float64
 10  Type_pregnancy              410 non-null    float64
 11  sex_baby1                   410 non-null    float64
 12  CBTS_M_3                    410 non-null    float64
 13  CBTS_M_4                    410 non-null    float64
 14  CBTS_M_5                    410 non-null    float64
 15  CBTS_M_6                    410 non-null    float64
 16  CBTS_M_7                    410 non-null    float64
 17  CBTS_M_8                    410 non-null    float64
 18  CBTS_M_9                    410 non-null    float64
 19  CBTS_M_10                   410 non-null    float64
 20  CBTS_M_11                   410 non-null    float64
 21  CBTS_M_12                   410 non-null    float64
 22  CBTS_13                     410 non-null    float64
 23  CBTS_14                     410 non-null    float64
 24  CBTS_15                     410 non-null    float64
 25  CBTS_16                     410 non-null    float64
 26  CBTS_17                     410 non-null    float64
 27  CBTS_18                     410 non-null    float64
 28  CBTS_19                     410 non-null    float64
 29  CBTS_20                     410 non-null    float64
 30  CBTS_21                     410 non-null    float64
 31  CBTS_22                     410 non-null    float64
 32  EPDS_1                      410 non-null    float64
 33  EPDS_2                      410 non-null    float64
 34  EPDS_3                      410 non-null    float64
 35  EPDS_4                      410 non-null    float64
 36  EPDS_5                      410 non-null    float64
 37  EPDS_6                      410 non-null    float64
 38  EPDS_7                      410 non-null    float64
 39  EPDS_8                      410 non-null    float64
 40  EPDS_9                      410 non-null    float64
 41  EPDS_10                     410 non-null    float64
 42  HADS_1                      410 non-null    float64
 43  HADS_3                      410 non-null    float64
 44  HADS_5                      410 non-null    float64
 45  HADS_7                      410 non-null    float64
 46  HADS_9                      410 non-null    float64
 47  HADS_11                     410 non-null    float64
 48  HADS_13                     410 non-null    float64
 49  Child_survey_participation  410 non-null    float64
 50  Age_bb                      410 non-null    float64
 51  IBQ_R_VSF_3_bb1             405 non-null    float64
 52  IBQ_R_VSF_4_bb1             377 non-null    float64
 53  IBQ_R_VSF_9_bb1             376 non-null    float64
 54  IBQ_R_VSF_10_bb1            375 non-null    float64
 55  IBQ_R_VSF_16_bb1            394 non-null    float64
 56  IBQ_R_VSF_17_bb1            329 non-null    float64
 57  IBQ_R_VSF_28_bb1            347 non-null    float64
 58  IBQ_R_VSF_29_bb1            395 non-null    float64
 59  IBQ_R_VSF_32_bb1            378 non-null    float64
 60  IBQ_R_VSF_33_bb1            326 non-null    float64
 61  Sleep_night_duration_bb1    410 non-null    object
 62  night_awakening_number_bb1  410 non-null    float64
 63  how_falling_asleep_bb1      410 non-null    float64
dtypes: float64(62), object(2)
memory usage: 511.9+ MB

In [14]:
feeding_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   S/n                    720 non-null    int64
 1   Weight                 720 non-null    float64
 2   Height                 720 non-null    float64
 3   Month                  720 non-null    object
 4   Breastfeeding Partern  720 non-null    object
dtypes: float64(2), int64(1), object(2)
memory usage: 28.3+ KB