# Exploring factors affecting infant sleep patterns: The role of feeding and developement

**Course:** Data Science - Final project

**Author:** Nikolay Atanasov | **Date:** April 13

---

In [24]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import os

## 1. Introduction
This project aims to explore factors that influence **infant sleep patterns** using multiple datasets.

## 2. Data Sources

In [25]:
# We use this to list all files and directories in our deffault directory
os.listdir()

['.git',
 '.ipynb_checkpoints',
 '.virtual_documents',
 'anaconda_projects',
 'Dataset_maternal_mental_health_infant_sleep.csv',
 'Data_Science_project.ipynb',
 'Weights heights of Infants with respect to method of feeding.xlsx']

In [23]:
# Dataset 1: Infant sleep
sleep_df = pd.read_csv("Dataset_maternal_mental_health_infant_sleep.csv", encoding = "latin1")

# Dataset 2: The role of feeding
feeding_df = pd.read_excel("Weights heights of Infants with respect to method of feeding.xlsx")

C:\Users\liyag\AppData\Local\Temp\ipykernel_1064\2546471507.py:2: DtypeWarning: Columns (6,61) have mixed types. Specify dtype option on import or set low_memory=False.
  sleep_df = pd.read_csv("Dataset_maternal_mental_health_infant_sleep.csv", encoding = "latin1")

## 3. Data Understanding

In [4]:
sleep_df.head()

,Participant_number,Type_parents,Birth_1mth_M_inclusion,Birth_12mth_M_inclusion,Age,Marital_status,Marital_status_Autre,Marital_status_edit,Education,Gestationnal_age,...,IBQ_R_VSF_10_bb1,IBQ_R_VSF_16_bb1,IBQ_R_VSF_17_bb1,IBQ_R_VSF_28_bb1,IBQ_R_VSF_29_bb1,IBQ_R_VSF_32_bb1,IBQ_R_VSF_33_bb1,Sleep_night_duration_bb1,night_awakening_number_bb1,how_falling_asleep_bb1
0,1.0,1.0,1.0,1.0,34.0,2.0,NaN,2.0,5.0,37.0,...,NaN,7.0,NaN,NaN,7.0,6.0,NaN,10:00,3.0,2.0
1,2.0,1.0,1.0,1.0,33.0,2.0,NaN,2.0,5.0,42.0,...,2.0,3.0,2.0,2.0,2.0,3.0,4.0,11:00,0.0,4.0
2,3.0,1.0,1.0,1.0,37.0,2.0,NaN,2.0,5.0,41.0,...,4.0,4.0,3.0,1.0,4.0,NaN,NaN,12:00,1.0,2.0
3,4.0,1.0,1.0,1.0,31.0,2.0,NaN,2.0,5.0,37.5,...,1.0,3.0,NaN,NaN,NaN,5.0,NaN,11:00,2.0,1.0
4,5.0,1.0,1.0,1.0,36.0,1.0,NaN,1.0,5.0,40.0,...,4.0,2.0,2.0,4.0,5.0,6.0,6.0,10:30,1.0,4.0

In [5]:
feeding_df.head()

   S/n  Weight  Height    Month    Breastfeeding Partern
0    1     4.0    17.0  Month 1  Exclusive Breastfeeding
1    2     4.9    18.5  Month 1  Exclusive Breastfeeding
2    3     5.2    16.0  Month 1  Exclusive Breastfeeding
3    4     4.5    18.0  Month 1  Exclusive Breastfeeding
4    5     5.5    19.0  Month 1  Exclusive Breastfeeding

In [6]:
sleep_df.shape

(1048292, 64)

In [7]:
feeding_df.shape

(720, 5)

In [8]:
sleep_df.columns

Index(['Participant_number', 'Type_parents', 'Birth_1mth_M_inclusion',
       'Birth_12mth_M_inclusion', 'Age', 'Marital_status',
       'Marital_status_Autre', 'Marital_status_edit', 'Education',
       'Gestationnal_age', 'Type_pregnancy', 'sex_baby1', 'CBTS_M_3',
       'CBTS_M_4', 'CBTS_M_5', 'CBTS_M_6', 'CBTS_M_7', 'CBTS_M_8', 'CBTS_M_9',
       'CBTS_M_10', 'CBTS_M_11', 'CBTS_M_12', 'CBTS_13', 'CBTS_14', 'CBTS_15',
       'CBTS_16', 'CBTS_17', 'CBTS_18', 'CBTS_19', 'CBTS_20', 'CBTS_21',
       'CBTS_22', 'EPDS_1', 'EPDS_2', 'EPDS_3', 'EPDS_4', 'EPDS_5', 'EPDS_6',
       'EPDS_7', 'EPDS_8', 'EPDS_9', 'EPDS_10', 'HADS_1', 'HADS_3', 'HADS_5',
       'HADS_7', 'HADS_9', 'HADS_11', 'HADS_13', 'Child_survey_participation',
       'Age_bb', 'IBQ_R_VSF_3_bb1', 'IBQ_R_VSF_4_bb1', 'IBQ_R_VSF_9_bb1',
       'IBQ_R_VSF_10_bb1', 'IBQ_R_VSF_16_bb1', 'IBQ_R_VSF_17_bb1',
       'IBQ_R_VSF_28_bb1', 'IBQ_R_VSF_29_bb1', 'IBQ_R_VSF_32_bb1',
       'IBQ_R_VSF_33_bb1', 'Sleep_night_duration_bb1',
       'night_awakening_number_bb1', 'how_falling_asleep_bb1'],
      dtype='object')

In [9]:
feeding_df.columns

Index(['S/n', 'Weight', 'Height', 'Month', 'Breastfeeding Partern'], dtype='object')

In [10]:
sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048292 entries, 0 to 1048291
Data columns (total 64 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Participant_number          410 non-null    float64
 1   Type_parents                410 non-null    float64
 2   Birth_1mth_M_inclusion      410 non-null    float64
 3   Birth_12mth_M_inclusion     410 non-null    float64
 4   Age                         410 non-null    float64
 5   Marital_status              410 non-null    float64
 6   Marital_status_Autre        2 non-null      object
 7   Marital_status_edit         410 non-null    float64
 8   Education                   410 non-null    float64
 9   Gestationnal_age            410 non-null    float64
 10  Type_pregnancy              410 non-null    float64
 11  sex_baby1                   410 non-null    float64
 12  CBTS_M_3                    410 non-null    float64
 13  CBTS_M_4                    410 non-null    float64
 14  CBTS_M_5                    410 non-null    float64
 15  CBTS_M_6                    410 non-null    float64
 16  CBTS_M_7                    410 non-null    float64
 17  CBTS_M_8                    410 non-null    float64
 18  CBTS_M_9                    410 non-null    float64
 19  CBTS_M_10                   410 non-null    float64
 20  CBTS_M_11                   410 non-null    float64
 21  CBTS_M_12                   410 non-null    float64
 22  CBTS_13                     410 non-null    float64
 23  CBTS_14                     410 non-null    float64
 24  CBTS_15                     410 non-null    float64
 25  CBTS_16                     410 non-null    float64
 26  CBTS_17                     410 non-null    float64
 27  CBTS_18                     410 non-null    float64
 28  CBTS_19                     410 non-null    float64
 29  CBTS_20                     410 non-null    float64
 30  CBTS_21                     410 non-null    float64
 31  CBTS_22                     410 non-null    float64
 32  EPDS_1                      410 non-null    float64
 33  EPDS_2                      410 non-null    float64
 34  EPDS_3                      410 non-null    float64
 35  EPDS_4                      410 non-null    float64
 36  EPDS_5                      410 non-null    float64
 37  EPDS_6                      410 non-null    float64
 38  EPDS_7                      410 non-null    float64
 39  EPDS_8                      410 non-null    float64
 40  EPDS_9                      410 non-null    float64
 41  EPDS_10                     410 non-null    float64
 42  HADS_1                      410 non-null    float64
 43  HADS_3                      410 non-null    float64
 44  HADS_5                      410 non-null    float64
 45  HADS_7                      410 non-null    float64
 46  HADS_9                      410 non-null    float64
 47  HADS_11                     410 non-null    float64
 48  HADS_13                     410 non-null    float64
 49  Child_survey_participation  410 non-null    float64
 50  Age_bb                      410 non-null    float64
 51  IBQ_R_VSF_3_bb1             405 non-null    float64
 52  IBQ_R_VSF_4_bb1             377 non-null    float64
 53  IBQ_R_VSF_9_bb1             376 non-null    float64
 54  IBQ_R_VSF_10_bb1            375 non-null    float64
 55  IBQ_R_VSF_16_bb1            394 non-null    float64
 56  IBQ_R_VSF_17_bb1            329 non-null    float64
 57  IBQ_R_VSF_28_bb1            347 non-null    float64
 58  IBQ_R_VSF_29_bb1            395 non-null    float64
 59  IBQ_R_VSF_32_bb1            378 non-null    float64
 60  IBQ_R_VSF_33_bb1            326 non-null    float64
 61  Sleep_night_duration_bb1    410 non-null    object
 62  night_awakening_number_bb1  410 non-null    float64
 63  how_falling_asleep_bb1      410 non-null    float64
dtypes: float64(62), object(2)
memory usage: 511.9+ MB

In [11]:
feeding_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   S/n                    720 non-null    int64
 1   Weight                 720 non-null    float64
 2   Height                 720 non-null    float64
 3   Month                  720 non-null    object
 4   Breastfeeding Partern  720 non-null    object
dtypes: float64(2), int64(1), object(2)
memory usage: 28.3+ KB

In [13]:
sleep_df.describe()

,Participant_number,Type_parents,Birth_1mth_M_inclusion,Birth_12mth_M_inclusion,Age,Marital_status,Marital_status_edit,Education,Gestationnal_age,Type_pregnancy,...,IBQ_R_VSF_9_bb1,IBQ_R_VSF_10_bb1,IBQ_R_VSF_16_bb1,IBQ_R_VSF_17_bb1,IBQ_R_VSF_28_bb1,IBQ_R_VSF_29_bb1,IBQ_R_VSF_32_bb1,IBQ_R_VSF_33_bb1,night_awakening_number_bb1,how_falling_asleep_bb1
count,410.000000,410.0,410.0,410.0,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,...,376.000000,375.000000,394.000000,329.000000,347.000000,395.000000,378.000000,326.000000,410.000000,410.000000
mean,205.500000,1.0,1.0,1.0,30.197561,2.002439,1.982927,4.080488,39.114146,1.012195,...,3.960106,3.360000,3.195431,2.477204,2.927954,4.326582,4.246032,3.634969,1.439024,3.041463
std,118.501055,0.0,0.0,0.0,4.362262,0.359970,0.225948,1.001642,1.900777,0.109890,...,1.973424,1.969283,1.773391,1.481676,2.121456,1.839272,1.725237,2.176491,1.589218,1.397076
min,1.000000,1.0,1.0,1.0,19.000000,1.000000,1.000000,1.000000,26.500000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,103.250000,1.0,1.0,1.0,27.000000,2.000000,2.000000,3.000000,38.000000,1.000000,...,2.000000,2.000000,2.000000,1.000000,1.000000,3.000000,3.000000,2.000000,0.000000,2.000000
50%,205.500000,1.0,1.0,1.0,30.000000,2.000000,2.000000,4.000000,39.200000,1.000000,...,4.000000,3.000000,3.000000,2.000000,2.000000,4.000000,4.000000,3.000000,1.000000,4.000000
75%,307.750000,1.0,1.0,1.0,33.000000,2.000000,2.000000,5.000000,40.400000,1.000000,...,6.000000,5.000000,4.000000,3.000000,5.000000,6.000000,6.000000,6.000000,2.000000,4.000000
max,410.000000,1.0,1.0,1.0,47.000000,6.000000,3.000000,5.000000,43.000000,2.000000,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,10.000000,5.000000

In [15]:
feeding_df.describe()

              S/n      Weight      Height
count  720.000000  720.000000  720.000000
mean   360.500000    6.040417   20.503056
std    207.990384    1.298707    2.333905
min      1.000000    2.300000   15.000000
25%    180.750000    5.200000   18.800000
50%    360.500000    6.000000   20.450000
75%    540.250000    7.000000   22.225000
max    720.000000   11.200000   26.700000

## 4. Data Cleaning

In [14]:
sleep_df.isna().sum()

Participant_number            1047882
Type_parents                  1047882
Birth_1mth_M_inclusion        1047882
Birth_12mth_M_inclusion       1047882
Age                           1047882
                               ...
IBQ_R_VSF_32_bb1              1047914
IBQ_R_VSF_33_bb1              1047966
Sleep_night_duration_bb1      1047882
night_awakening_number_bb1    1047882
how_falling_asleep_bb1        1047882
Length: 64, dtype: int64

In [18]:
sleep_df = sleep_df.dropna(how = 'all')

In [19]:
sleep_df.shape

(410, 64)

In [20]:
sleep_df.isna().sum()

Participant_number             0
Type_parents                   0
Birth_1mth_M_inclusion         0
Birth_12mth_M_inclusion        0
Age                            0
                              ..
IBQ_R_VSF_32_bb1              32
IBQ_R_VSF_33_bb1              84
Sleep_night_duration_bb1       0
night_awakening_number_bb1     0
how_falling_asleep_bb1         0
Length: 64, dtype: int64

In [16]:
feeding_df.isna().sum()

S/n                      0
Weight                   0
Height                   0
Month                    0
Breastfeeding Partern    0
dtype: int64